### ISSUE TITLE
Add support for webpack (CommonJS)

### ISSUE THREAD

**Issue by dsge** [schalkt/angular-super-gallery#1]
( After #2 is done: )
```
npm install angular-super-gallery --save
```
Webpack support will allow the library to be used like this in our projects :thumbsup: :
---

```js
//index.js in my project

var angular = require("angular");

angular.module("myApp", [
    require("angular-super-gallery"),
]);
```

Right now I would have to do something like this :thumbsdown: : 
---
```js
//index.js in my project

var angular = require("angular");

require("angular-super-gallery"); //return value is useless

angular.module("myApp", [
    'angularSuperGallery', //had to open the source code on github to get the name of the module
]);
```

Example libraries that have webpack support:
---
- angular-ui-bootstrap
- satellizer
- angular-ui-router
- angular-messages
- angular-resource
- angular-sanitize
- ng-file-upload

**Comment by schalkt** [comment]
done ;)
