### ISSUE TITLE
Add dependencies to package.json as well

### ISSUE THREAD

**Issue by dsge** [schalkt/angular-super-gallery#3]
In `readme.md`:

> ### Requirements
> - [angular](https://github.com/angular/angular.js/tree/v1.6.4) 1.6.4
> - [angular-animate](https://github.com/angular/bower-angular-animate/tree/v1.6.4) 1.6.4
> - [angular-touch](https://github.com/angular/bower-angular-touch/tree/v1.6.4) 1.6.4
> - [angular-fullscreen](https://github.com/fabiobiondi/angular-fullscreen) 1.0.1 
> - [bootstrap](https://github.com/twbs/bootstrap/tree/v3.3.7) 3.3.7

However in `package.json`  4 of the dependencies are missing:
```
"dependencies": {
    "angular-fullscreen": "git+https://github.com/fabiobiondi/angular-fullscreen.git"
}
```

**Comment by schalkt** [comment]
fixed
