### ISSUE TITLE
angular-super-gallery.js

### ISSUE THREAD

**Issue by safaEF** [schalkt/angular-super-gallery#40]
Hello, 
when i installed the library and try to work with it i have this error "ERROR in ./node_modules/angular-super-gallery/index.js
Module not found: Error: Can't resolve './dist/angular-super-gallery.js' " so i try to this file and insert it to my project and then i get this error " ReferenceError: angular is not defined at angular-super-gallery.js:10:1 "  i think is in this line 
" var app = angular.module('angularSuperGallery', ['ngAnimate', 'ngTouch']); "
so if there is a solution for that because i need to work with this library!
thank you

**Comment by schalkt** [comment]
Hello,
For this gallery you need the AngularJS framework
```npm install angular@1.8.2``` or download from here : https://angularjs.org/ ( DOWNLOAD ANGULARJS button )

**Comment by safaEF** [comment]
thanks for response, but i am using angular8 , it will work ?

**Comment by schalkt** [comment]
Unfortunately no, it only works with AngularJS
