### ISSUE TITLE
Reload component

### ISSUE THREAD

**Issue by rabbishuki** [schalkt/angular-super-gallery#8]
Hi there,

You have built a pretty robust component, and I am loving it, but can you please help me with a small issue that I have.

If the data in the array of images changes, for some reason the images don't change.
I am guessing that you disabled the $watch for performance reasons.

But my question is:
Is there a way to reload this component when new data comes in?

**Comment by schalkt** [comment]
Hello,

This is a good question. :)
Currently not available the dynamic reload of images, but I am working on it and release as soon as possible. (approx. 2-3 days)

**Comment by rabbishuki** [comment]
That would be amazing!

Please let me know when it is done.

Thank you so much.

**Comment by schalkt** [comment]
Done :)
Call this event when the images in the array are changed:

```javascript
$rootScope.$broadcast('ASG-gallery-edit', {
   id: 'nature',
   refresh: true
});
```
See more examples in the demo/demo.js file.

The $watch function not working in the gallery engine, because the original array of images is transferred to another array.

**Comment by rabbishuki** [comment]
Wow, you are quick!

It is working, but for some reason, it is adding the new images on to the old ones.

I had 2 images, and changed the array to 2 new images and now I have 4!

tried changing the event to `ASG-gallery-updated` but didn't help either.

Am I missing something?

**Comment by schalkt** [comment]
Try to use only the **update** method. The **refresh** is problematic when used with update, add or delete. (I think I will delete the **refresh** from the next version.)

```
$rootScope.$broadcast('ASG-gallery-edit', {
	id: 'yourGalleryId',
	update: yourGalleryImages
});
```

**Comment by rabbishuki** [comment]
OK, and `yourGalleryImages` needs to be replaced with the new array?

**Comment by schalkt** [comment]
You can use the original array or a whole new array.

```
var yourGalleryImages = [imageObject1, imageObject2, etc.]

//----------- add new image with using original array
yourGalleryImages.push(imageObject3);
$rootScope.$broadcast('ASG-gallery-edit', {
	id: 'yourGalleryId',
	update: yourGalleryImages
});

//----------- overwrite the gallery with new images array
var yourGalleryImages2 =  [imageObject4, imageObject5, etc.]
$rootScope.$broadcast('ASG-gallery-edit', {
	id: 'yourGalleryId',
	update: yourGalleryImages2
});
```

**Comment by rabbishuki** [comment]
I tried but it also gives me the old array in addition to the new array.

**Comment by schalkt** [comment]
Can you show this part of your code?
Try to update ASG to v1.4.3

**Comment by aheadwebcloud** [comment]
Hi,

I am facing the same issue.
I am using this component for image gallery uploaded by user for the events. Each user has its own gallery. 

images array includes all the users gallery into single array and displays all in one gallery. Every time it is adding the image into the array.

Is there any way to avoid this issue.

**Comment by schalkt** [comment]
Hi,

Each gallery have different id in HTML? 
```HTML
<asg-image id="user11_gallery"> ...... </asg-image>
<asg-image id="user22_gallery"> ...... </asg-image>
```

**Comment by aheadwebcloud** [comment]
OK Thanks, It works.  

One more issue is repeatedly adding the same array values. 

if i have 3 images first time then again adding 3 same images after revisit the page has gallery and becomes 6 images and so on...

Please guide.

**Comment by schalkt** [comment]
Ok, I've added new option to the config in the version 1.4.5:
``` { "duplicates" : false, // or true, default false ```
So if you add same image(s) to the gallery there are not visible in default.

**Comment by aheadwebcloud** [comment]
Thanks, Updated to 1.4.5 and added option. It works .
